project:
  type: book
  output-dir: docs
  
book:
  title: "Geocomputation with Python"
  author: "TBC"
  description: | 
    Work in Progress 🎉
  cover-image: https://geocompr.robinlovelace.net/images/cover.png
  site-url: https://geocompr.github.io
  repo-url: https://github.com/geocompr/pytest/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-spatial-data.qmd
  appendices:

format:
  html: 
    theme: cosmo
    cover-image: cover.png
    code-link: true


