on:
  push:
    branches:
      quartotest
name: Render
jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    container: geocompr/geocompr:python
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render Book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd")'
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        run: |
          quarto --version
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          publish_branch: gh-pages
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'