name: PRs
on: pull_request

jobs:
  bookdown:
    name: Test-quarto
    runs-on: ubuntu-latest
    container: geocompr/geocompr:conda
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: |
          conda activate geocompy
          # test code:
          ./convert.sh
          ./run-code.sh
          quarto render
          ls docs
